fast/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.contrib.auth.views import password_reset, password_reset_done, password_reset_confirm, password_reset_complete
from apps.financeiro.views import CreditoMensagemCreateView
import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^ckeditor/', include('ckeditor.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),

    url(r'^esqueceu-a-senha/$', password_reset,
        {'post_reset_redirect' : '/esqueceu-a-senha/concluido/'}, name='esqueceu_senha'),
    (r'^esqueceu-a-senha/concluido/$', password_reset_done),
    url(r'^esqueceu-a-senha/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,
        {'post_reset_redirect' : '/esqueceu-a-senha/completo/'}),
    (r'^esqueceu-a-senha/completo/$', password_reset_complete),
    (r'^selectable/', include('selectable.urls')),
)

urlpatterns += patterns('apps.mensagem.views',
    url(r'login/$', 'login', name='login'),
    url(r'^sair/$', 'sair'),
    url(r'^registrar/$', 'registrar'), # pagina de cadastro
    url(r'^editar-perfil/$', 'editar_perfil', name='editar-perfil'), # pagina de cadastro
    url(r'^mensagem/$', 'enviar', name='enviar'), # pagina de envio
    url(r'^mensagem-direta/(\d+)/$', 'mensagem_direta'),
    url(r'^adicionar-contato/$', 'adicionar', name='adicionar_contato'),
    url(r'^adicionar-grupo/$', 'adicionar_grupo', name='adicionar_grupo'),
    url(r'^importar/$', 'importar'),
    url(r'^editar-contato/(\d+)/$', 'editar'),
    url(r'^contatos/$', 'mostrar_contato', name='contatos'),
    url(r'^load-contato/(\d+)/$', 'load_contato',name='load_contato'),
    url(r'^grupos/$', 'mostrar_grupo', name='grupos'),
    url(r'^grupo/(\d+)/contatos/$', 'contato_grupo', name='contato_grupo'),
    url(r'^editar-grupo/(\d+)/$', 'editar_grupo'),
    url(r'^colaboradores/$', 'mostrar_colaborador', name='colaboradores'),
    url(r'^adicionar_colaborador/(\d+)/$', 'deletar_colaborador'),
    url(r'^deletar_contato/(\d+)/$', 'deletar_contato'),
    url(r'^deletar_grupo/(\d+)/$', 'deletar_grupo'),
    url(r'^deletar_colaborador/(\d+)/$', 'deletar_colaborador'),
    url(r'^adicionar_creditos_colaborador/(\d+)/$', 'adicionar_creditos_colaborador'),
    url(r'^registrar/$', 'registrar', name='registrar'),
    url(r'^deletar-contato/(\d+)/$', 'deletar_contato'),
    url(r'^deletar-grupo/(\d+)/$', 'deletar_grupo'),
    url(r'^deletar-colaborador/(\d+)/$', 'deletar_colaborador'),
    url(r'^adicionar-colaborador/$', 'adicionar_colaborador'),
    url(r'^busca-grupo/$', 'busca_grupo'),
    url(r'^busca-colaborador/$', 'busca_colaborador'),
    url(r'^busca-contato/$', 'busca_contato'),
    url(r'^busca-contato-grupo/(\d+)/$', 'busca_contato_grupo'),
    url(r'^busca-sms/$', 'busca_sms'),
    url(r'^historico-sms/$', 'historico_sms', name='historico_sms'),
    url(r'^api/enviar-sms/$', 'api_enviar_sms', name='api_enviar_sms'),
)

urlpatterns += patterns('apps.website.views',
    url(r'^$', 'homepage', name='home'),
    url(r'^contato/$', 'contato', name='contato'),
    url(r'^solucoes/$', 'solucoes', name='solucoes'),
    url(r'^blog/(?P<slug>[\w_-]+)-(?P<id>\d+).html', 'noticia'),
    url(r'^blog/', 'noticias', name='blog')
)

urlpatterns += patterns('apps.financeiro.views',
    url(r'comprar-credito/$', CreditoMensagemCreateView.as_view(), name='comprar_credito'),
    url(r'notificacao/$', 'aprovar_pagamento', name='notificacao'),
    url(r'^historico-credito/$', 'historico_credito', name='historico_credito'),
    url(r'^busca-credito/$', 'busca_credito'),
)

apps/financeiro/models.py
# coding=utf-8
from datetime import datetime
from ckeditor.fields import RichTextField
from django.db import models
from django.db.models.signals import post_save
from apps.mensagem.models import Usuario


class Vendedor(models.Model):
    nome = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(verbose_name='Email', max_length=255, unique=True, db_index=True, )
    telefone = models.CharField(max_length=11)
    endereco = models.CharField('Endereço', max_length=200, null=True, blank=True)
    dt_nasc = models.DateField('Data de Nascimento', null=True, blank=True)

    def __unicode__(self):
        return '%s - %s - %s' % (self.nome, self.email, self.telefone)


class PacoteMensagem(models.Model):
    ativo = models.BooleanField(default=True)
    nome = models.CharField(max_length=150)
    descricao = RichTextField()
    quantidade_inicial = models.IntegerField()
    quantidade_final = models.IntegerField()
    imagem = models.ImageField(upload_to='uploads/planos')
    valor = models.DecimalField(max_digits=3, decimal_places=2)
    usuario = models.ForeignKey(Usuario)
    dt_criacao = models.DateTimeField('Criado em', default=datetime.now)

    def __unicode__(self):
        return '%s - %s' % (self.nome, self.usuario.nome)


class CreditoMensagem(models.Model):
    """Classe de compra de Mensagem"""
    quantidade = models.IntegerField()
    status = models.BooleanField(default=False)
    referencia = models.CharField(max_length=150, blank=True, null=True)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    usuario = models.ForeignKey(Usuario)
    vendedor = models.ForeignKey(Vendedor, blank=True, null=True)
    pacote_mensagem = models.ForeignKey(PacoteMensagem)
    dt_criacao = models.DateTimeField('Criado em', default=datetime.now)

    def __unicode__(self):
        return '%s' % self.usuario


def atualiza_vendedor(sender, instance, **kwargs):
    if instance.referencia:
        credito_historico = CompraCreditoHistorico.objects.get(referencia__exact=instance.referencia)
        credito_historico.vendedor = instance.vendedor
        credito_historico.save()


post_save.connect(atualiza_vendedor, sender=CreditoMensagem, )


def atualiza_creditos(sender, instance, **kwargs):
    if instance.status:
        instance.usuario.creditos += int(instance.quantidade)
        instance.usuario.save()


post_save.connect(atualiza_creditos, sender=CreditoMensagem, )


class CompraCreditoHistorico(models.Model):
    TIPO_PAGAMENTO_CHOICES = (
        ('1', 'Cartão de crédito'), ('2', 'Boleto'), ('3', 'Débito online (TEF)'), ('4', 'Saldo PagSeguro'),
        ('5', 'Oi Paggo'), ('7', 'Depósito em conta'),)
    usuario = models.ForeignKey(Usuario)
    vendedor = models.ForeignKey(Vendedor, blank=True, null=True)
    pacote_mensagem = models.ForeignKey(PacoteMensagem)
    quantidade = models.IntegerField()
    valor_pacote = models.DecimalField(max_digits=10, decimal_places=2)
    valor_total_compra = models.DecimalField(max_digits=10, decimal_places=2)
    dt_criacao = models.DateTimeField('Criado em', default=datetime.now)
    dt_final = models.DateTimeField('Atualizado em', default=datetime.now)
    tipo_pagamento = models.CharField(max_length=150, blank=True, null=True, choices=TIPO_PAGAMENTO_CHOICES)
    num_parcelas = models.IntegerField(default=0, blank=True, null=True)
    status = models.BooleanField(default=False, )
    referencia = models.CharField(max_length=150, blank=True, null=True)

    def __unicode__(self):
        return '%s - %s - %d' % (self.usuario.nome, self.pacote_mensagem.nome, self.quantidade)

apps/mensagem/models.py
# -*- coding: utf-8 -*-
from datetime import datetime
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class UsuarioManager(BaseUserManager):
    def create_user(self, email, nome, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(email=self.normalize_email(email), nome=nome)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nome, password):
        user = self.create_user(email, nome, password=password, )
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Usuario(AbstractBaseUser):
    email = models.EmailField(verbose_name='Email', max_length=255, unique=True, db_index=True, )
    colaboradores = models.ManyToManyField('self', through='SocioColaboradores', symmetrical=False)
    telefone = models.CharField(max_length=15)
    nome = models.CharField(max_length=200, null=True, blank=True)
    endereco = models.CharField('Endereço', max_length=200, null=True, blank=True)
    profissao = models.CharField('Profissão', max_length=200, null=True, blank=True)
    empresa = models.CharField(max_length=200, null=True, blank=True)
    dt_nasc = models.DateField('Data de Nascimento', null=True, blank=True)
    is_active = models.BooleanField('Ativo?', default=True)
    is_superuser = models.BooleanField('Administrador?', default=False)
    creditos = models.IntegerField('Créditos', default=20)

    objects = UsuarioManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['telefone']

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_superuser


class SocioColaboradores(models.Model):
    socio = models.ForeignKey(Usuario, related_name='socio')
    colaborador = models.ForeignKey(Usuario, related_name='colaborador')
    descricao = models.CharField('Descrição', max_length=200, null=True, blank=True)
    contador_mensagem = models.IntegerField(default=0)
    limite = models.IntegerField()

    class Meta:
        verbose_name = 'Socio e Colaborador'
        verbose_name_plural = 'Sócios e Colaboradores'

    def __unicode__(self):
        return '%s' % self.socio

    def get_credito_disponivel(self):
        disponivel = self.limite - self.contador_mensagem
        return disponivel

    def clean(self):
        try:
            colaborador = self.colaborador
        except:
            raise ValidationError('Usuário não cadastrado')


class Grupo(models.Model):
    nome = models.CharField(max_length=200)
    usuario = models.ForeignKey(Usuario)

    def __unicode__(self):
        return self.nome


class Contato(models.Model):
    nome = models.CharField(max_length=200, null=True, blank=True)
    usuario = models.ForeignKey(Usuario)
    endereco = models.CharField('Endereço', max_length=200, null=True, blank=True)
    profissao = models.CharField('Profissão', max_length=200, null=True, blank=True)
    empresa = models.CharField(max_length=200, null=True, blank=True)
    dt_nasc = models.DateField('Data de Nascimento', null=True, blank=True)

    def __unicode__(self):
        return self.nome


class Telefone(models.Model):
    descricao = models.CharField(max_length=200, null=True, blank=True)
    #variavel com o nome usuario_telefone ao invez de usuario por conta de um problema no south
    usuario_telefone = models.ForeignKey(Usuario, blank=True, null=True, related_name='usuario_telefone')
    telefone = models.CharField(max_length=15)
    contato = models.ForeignKey(Contato)
    grupo = models.ManyToManyField(Grupo, null=True, blank=True)

    def __unicode__(self):
        return self.telefone

    def clean(self):
        telefones = Telefone.objects.filter(telefone=self.telefone, usuario_telefone=self.usuario_telefone)
        if telefones.exists():
            raise ValidationError('O telefone cadastrado ja existe')


class Mensagem(models.Model):
    msg = models.CharField('Mensagem', max_length=160)
    usuario = models.ForeignKey(Usuario)
    dt_criacao = models.DateTimeField('Criado em', default=datetime.now)
    dt_envio = models.DateTimeField('Data de Envio', default=datetime.now)
    is_api = models.BooleanField('Api?', default=False)
    telefone = models.ManyToManyField(Telefone, null=True, blank=True)
    grupo = models.ManyToManyField(Grupo, null=True, blank=True)

    class Meta:
        verbose_name = 'Mensagem'
        verbose_name_plural = 'Mensagens'

    def __unicode__(self):
        return '%s' % self.msg


class HistoricoMensagem(models.Model):
    STATUS_SMS_CHOICES = (('1', 'Pendente'), ('2', 'Enviada'), ('3', 'Cancelada'))

    usuario_remetente = models.ForeignKey(Usuario)
    contato_destinatario = models.CharField(max_length=200)
    msg = models.ForeignKey(Mensagem)
    dt_criacao = models.DateTimeField('Criado em', default=datetime.now)
    status = models.CharField(max_length=2, blank=True, null=True, choices=STATUS_SMS_CHOICES)
    resposta_html = models.CharField(max_length=10, blank=True, null=True)
    resposta_api = models.CharField(max_length=50, blank=True, null=True)

    def __unicode__(self):
        return '%s' % self.dt_criacao

templates/servicos/addcolaborador.html
{% extends 'componentes/base.html' %}
{% load selectable_tags %}
{% include_jquery_libs %}
{% block extracss %}
    <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/themes/base/jquery-ui.css"
          type="text/css">
    <link href="{{ STATIC_URL }}selectable/css/dj.selectable.css" type="text/css" media="all" rel="stylesheet">
{% endblock %}
{% block extrajs %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.0/jquery-ui.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}selectable/js/jquery.dj.selectable.js"></script>
{% endblock %}
{% block content %}
    <section id="container">
        <div class="row">
            <div class="large-9  medium-9 columns">
                <div class="row">
                    <div class="large-12  medium-12 columns">
                        <nav class="breadcrumbs">
                            <a href="{% url 'apps.mensagem.views.login' %}">Minha Conta</a>
                            <a href="{% url 'apps.mensagem.views.mostrar_colaborador' %}">Colaborares</a>
                            <a class="current" href="{{ request.path }}">Adicionar Colaborador</a>
                        </nav>
                    </div>
                </div>
                {% include 'componentes/mensagem-confirmacao.html' %}
                <div class="bg-panel">
                    <h4 class="titleheader">Adicionar colaborador</h4>
                    <div class="row">
                        <div class="large-6  medium-6 columns">
                            <form method="POST" action="{% url 'apps.mensagem.views.adicionar_colaborador' %}">
                                {% csrf_token %}
                                <input value="{{ request.user.id }}" type="hidden" name="socio"/>
                                <label {% if form.colaborador.errors %} class="error" {% endif %}>Email*:</label>
                                <input data-selectable-allow-new="false" data-selectable-type="text"
                                       data-selectable-url="/selectable/mensagem-usuarioslookup/" id="id_colaborador_0"
                                       name="colaborador_0" type="email"
                                       class="{% if form.colaborador.errors %} error {% endif %} ui-autocomplete-input ui-widget ui-widget-content ui-corner-all"
                                       placeholder="exemplo@exemplo.com" autocomplete="off">
                                <label {% if form.descricao.errors %} class="error" {% endif %}>Descrição:</label>
                                <input id="id_descricao" name="descricao" type="text"
                                       clas s="{% if form.descricao.errors %} error {% endif %} ui-autocomplete-input ui-widget ui-widget-content ui-corner-all"
                                       placeholder="Gerente de Setor" autocomplete="off">
                                {% if form.non_field_errors %}
                                <small class="error">{{ form.non_field_errors.as_text }}</small>
                                {% endif %}
                                <input data-selectable-type="hidden" id="id_colaborador_1" name="colaborador_1"
                                       type="hidden">
                                <label {% if form.limite.errors %} class="error" {% endif %}>Limite de SMS*:</label>
                                <input type="text" name="limite" placeholder="99" {% if form.limite.errors %} class="error" {% endif %}/>
                                {% if form.limite.errors %}
                                    <small class="error">{{ form.limite.errors.as_text }}</small>{% endif %}
                                <div class="btnadd">
                                    <ul class="button-group">
                                        <li>
                                            <button type="submit" class="button success small">Salvar</button>
                                        </li>
                                    </ul>
                                </div>
                            </form>
                        </div>
                        <div class="large-6  medium-6 columns">
                            <h4>Como adicionar um colaborador</h4>
                            <div class="passo-passo">
                                <p><strong>Passo 1: </strong> Certifique-se que o colaborador seja resgistrado no Komit</p>
                                <p><strong>Passo 2: </strong> Busque-o pelo email de cadastro</p>
                                <p><strong>Passo 3: </strong> Caso deseje, adicione uma descrição a ele</p>
                                <p><strong>Passo 4: </strong> Em "Limite de SMS" adicione a quantidade de mensagens que deseja transferir ao colaborador</p>
                                <p><strong>Passo 5: </strong> Para concluir, aperte no botão "Salvar"</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% include 'componentes/sidebar.html' %}
        </div>
    </section>

{% endblock %}

templates/servicos/addgrupo.html
{% extends 'componentes/base.html' %}
{% block extracss %}
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/chosen.css"/>
{% endblock %}
{% block content %}

    <section id="container">
        <div class="row">
            <div class="large-9  medium-9 columns">
                <div class="row">
                    <div class="large-12  medium-12 columns">
                        <nav class="breadcrumbs">
                            <a href="{% url 'apps.mensagem.views.login' %}">Minha Conta</a>
                            <a href="{% url 'apps.mensagem.views.mostrar_grupo' %}">Grupos</a>
                            <a class="current" href="{{ request.path }}">Adicionar grupo</a>
                        </nav>
                    </div>
                </div>
                {% include 'componentes/mensagem-confirmacao.html' %}
                <div class="bg-panel">
                    <div class="row">
                        <div class="large-12  medium-12 columns">
                            <h4 class="titleheader">Adicionar grupo</h4>
                            <form method="POST" action="{% url 'apps.mensagem.views.adicionar_grupo' %}"
                                  enctype="multipart/form-data">{% csrf_token %}
                                <input value="{{ request.user.id }}" type="hidden" name="grupo-usuario"/>

                                <div class="row">
                                    <div class="large-6  medium-6 columns">
                                        <label {% if form_grupo.nome.errors %} class="error" {% endif %}>Grupo:</label>
                                        <input type="text" name="grupo-nome" {% if form_grupo.nome.errors %} class="error" {% endif %}/>
                                        {% if form_grupo.nome.errors %}<small class="error">{{ form_grupo.nome.errors.as_text }}</small>{% endif %}
                                        <label {% if form_grupo.non_field_errors %} class="error" {% endif %}>Contatos</label>
                                        <select data-placeholder="Lista de contatos" name="grupo-contatos" multiple
                                                class="chosen-select {% if form_grupo.non_field_errors %}error{% endif %}">
                                            <option value=""></option>
                                            {% for contato in todos_contatos %}
                                                {% for telefone in contato.telefone_set.all %}
                                                    <option value="{{ telefone.pk }}">{{ contato.nome }}
                                                        ( {{ telefone.descricao }}: {{ telefone.telefone }} )
                                                    </option>
                                                {% endfor %}
                                            {% endfor %}
                                        </select>
                                        {% if form_grupo.non_field_errors %}
                                            <small class="error">{{ form_grupo.non_field_errors.as_text }}</small>{% endif %}
                                    </div>

                                    {#                                <div class="large-6  medium-6 columns">#}
                                    {#                                    <label>Upload arquivos CSV, TXT, vCard e Excel :</label>#}
                                    {#                                    <input type="file" name="arquivo" value="Selecione o arquivo" placeholder=""/>#}
                                    {#                                </div>#}
                                </div>

                                <div class="row">
                                    <div class="large-12  medium-12 columns">
                                        <div class="btnadd">
                                            <ul class="button-group">
                                                <li><a href="#panel2-2">
                                                    <button type="submit" class="button success small">Salvar</button>
                                                </a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>


            </div>

            {% include 'componentes/sidebar.html' %}
        </div>
    </section>

{% endblock %}

{% block extrajs %}
    <script src="{{ MEDIA_URL }}js/chosen.js"></script>
    <script type="text/javascript">
        var config = {
            '.chosen-select': {},
            '.chosen-select-deselect': {allow_single_deselect: true},
            '.chosen-select-no-single': {disable_search_threshold: 10},
            '.chosen-select-no-results': {no_results_text: 'Oops, nothing found!'},
            '.chosen-select-width': {width: "95%"}
        }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
    </script>
{% endblock %}

templates/servicos/comprar_credito.html
{% extends 'componentes/base.html' %}

{% block content %}
    <section id="container">
        <div class="row">
            <div class="large-9  medium-9 columns">
                <div class="row">
                    <div class="large-12  medium-12 columns">
                        <nav class="breadcrumbs">
                            <a href="{% url 'apps.mensagem.views.login' %}">Minha Conta</a>
                            <a class="current" href="{{ request.path }}">Comprar mais créditos</a>
                        </nav>
                    </div>
                </div>
                {% include 'componentes/mensagem-confirmacao.html' %}
                <div class="bg-panel">
                    <div class="row">
                        <div class="large-12  medium-12 columns">
                            <h4 class="titleheader">Planos tarifas</h4>
                            <ul class="small-block-grid-2 medium-block-grid-5 large-block-grid-5">
                                {% for plano in planos %}
                                <li>
                                    <div class="planobox">
                                        <img src="{{ MEDIA_URL }}{{ plano.imagem }}" alt="">
                                        <h6>R$ {{ plano.valor }} / SMS</h6>
                                        <h6>De <span>{{ plano.quantidade_inicial }}</span> até <span>{{ plano.quantidade_final }}</span>sms</h6>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>


                    <div class="row">
                        <form method="POST" action="{% url 'comprar_credito' %}">{% csrf_token %}
                            <div class="large-6  medium-6 columns">
                                {{ form.non_field_errors }}
                                <input value="{{ request.user.id }}" type="hidden" name="usuario"/>
                                <label>Quantidade de créditos</label>
                                <input id="id_quantidade" name="quantidade" type="text" placeholder="Digite a quantidade de SMS">
                                <div class="btnadd">
                                    <ul class="button-group">
                                        <li>
                                            <button type="submit" class="button success small">Comprar créditos</button>
                                        </li>
                                    </ul>
                                </div>
                                {{ form.msg.errors }}
                            </div>

                        </form>
                    </div>
                    <hr class="linha">
                    <h6>* SMS para todas as operadoras do Brasil</h6>

                </div>
            </div>
            {% include 'componentes/sidebar.html' %}
        </div>
    </section>

{% endblock %}

templates/servicos/editar_grupo.html
{% extends 'componentes/base.html' %}
{% block extracss %}
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/chosen.css"/>
{% endblock %}
{% block content %}

    <section id="container">
        <div class="row">
            <div class="large-9  medium-9 columns">
                <div class="row">
                    <div class="large-12  medium-12 columns">
                        <nav class="breadcrumbs">
                            <a href="{% url 'apps.mensagem.views.login' %}">Minha Conta</a>
                            <a href="{% url 'apps.mensagem.views.mostrar_grupo' %}">Grupos</a>
                            <a class="current" href="{{ request.path }}">Editar Grupo</a>
                        </nav>
                    </div>
                </div>
                {% include 'componentes/mensagem-confirmacao.html' %}
                <div class="bg-panel">
                    <div class="row">
                        <div class="large-12  medium-12 columns">
                            <h4 class="titleheader">Editar grupo</h4>
                            <form method="POST"
                                  action="{% url 'apps.mensagem.views.editar_grupo' grupo.id %}">{% csrf_token %}
                                {{ form_grupo.non_field_errors }}
                                <input value="{{ request.user.id }}" type="hidden" name="usuario"/>

                                <div class="row">
                                    <div class="large-12  medium-12 columns">
                                        {{ form_grupo.nome.errors }}
                                        <label>Nome:</label>
                                        <input type="text" name="nome" value="{{ grupo.nome }}"/>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="large-12  medium-12 columns">
                                        <label>Contatos</label>
                                        <select data-placeholder="Lista de contatos" name="grupo-contatos" multiple
                                                class="chosen-select">
                                            <option value=""></option>
                                            {% for contato in todos_contatos %}
                                                {% for telefone in contato.telefone_set.all %}
                                                    {% if telefone in grupo.telefone_set.all %}
                                                        <option selected value="{{ telefone.pk }}">{{ contato.nome }}
                                                            ( {{ telefone.descricao }}: {{ telefone.telefone }} )
                                                        </option>
                                                    {% else %}
                                                        <option value="{{ telefone.pk }}">{{ contato.nome }}
                                                            ( {{ telefone.descricao }}: {{ telefone.telefone }} )
                                                        </option>
                                                    {% endif %}
                                                {% endfor %}
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="btnadd">
                                    <ul class="button-group">
                                        <li>
                                            <button type="submit" class="button success small">Salvar</button>
                                        </li>
                                    </ul>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>


            </div>

            {% include 'componentes/sidebar.html' %}
        </div>
    </section>

{% endblock %}

{% block extrajs %}
    <script src="{{ MEDIA_URL }}js/chosen.js"></script>
    <script type="text/javascript">
        var config = {
            '.chosen-select': {},
            '.chosen-select-deselect': {allow_single_deselect: true},
            '.chosen-select-no-single': {disable_search_threshold: 10},
            '.chosen-select-no-results': {no_results_text: 'Oops, nothing found!'},
            '.chosen-select-width': {width: "95%"}
        }
        for (var selector in config) {
            $(selector).chosen(config[selector]);
        }
    </script>
{% endblock %}

templates/servicos/enviada.html
<!DOCTYPE html>
<html>
<head>
    <title>Enviar Mensagem</title>
</head>
<body>
<h1>Mensagem enviada com sucesso!</h1>
</body>
</html>